name: Deploy to Cloudflare Workers
on:
  pull_request:
    branches:
      - develop
      - master
    types: [closed]
jobs:
  deploy:
    name: Deploy workers
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Set environment
        run: |
          echo "ENVIRONMENT=$(if [[ '${{ github.event.pull_request.base.ref }}' == '${{ github.event.repository.default_branch }}' ]]; then echo 'production'; else echo 'development'; fi)" >> $GITHUB_ENV
      - name: Wrangler deploy
        uses: cloudflare/wrangler-action@v3
        env:
          ENVIRONMENT: ${{ github.event.pull_request.base.ref == 'master' && 'production' || 'development' }}
        with:
          wranglerVersion: latest
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env ${{ env.ENVIRONMENT }} --minify src/index.ts
